config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  resources:users

  get '/login', to: "users#login"
  post '/resoult', to: "users#resoult"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		end
	end

	def login
		@user = User.new
	end

	def resoult
		pp params[:user][:email]
		pp params[:user][:password]
		pp @user = User.find_by(email: params[:user ][:email], password: params[:user][:password])
		redirect_to user_path(@user.id)
 	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		if @user.save
			redirect_to user_path(@user.id)
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.delete(user_params)
		@user.save
	end

	private 
		def user_params
			params.require(:user).permit(:firstname, :lastname, :email, :password)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<%= link_to "Registration", new_user_path %>  
<%= link_to "Login" ,login_path %>

app/views/users/edit.html.erb
<%= form_for @user, url: user_path(@user.id) do |f| %>

<%= f.label :firstname %>  <br>
<%= f.text_field :firstname %>  <br>

<%= f.label :lastname %> <br>
<%= f.text_field :lastname %> <br>

<%= f.label :email %> <br>
<%= f.text_field :email %> <br>

<%= f.label :password %> <br>
<%= f.password_field :password %> <br>

<%= f.submit 'Save' %>
<% end %>

app/views/users/login.html.erb
<%= form_for @user, url: resoult_path do |f| %>

<%= f.label :email %> <br>
<%= f.text_field :email %> <br>

<%= f.label :password %> <br>
<%= f.password_field :password %> <br>

<%= f.submit 'Login' %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: users_path do |f| %>

<%= f.label :firstname %>  <br>
<%= f.text_field :firstname %>  <br>

<%= f.label :lastname %> <br>
<%= f.text_field :lastname %> <br>

<%= f.label :email %> <br>
<%= f.text_field :email %> <br>

<%= f.label :password %> <br>
<%= f.password_field :password %> <br>

<%= f.submit 'Save' %>
<% end %>

app/views/users/show.html.erb
Hello, <%= @user.firstname %> 
 <%= @user.lastname %> <br>
<%= link_to "Edit", edit_user_path(@user.id)%> <br>
<%= link_to 'delete', user_path, :method => :delete%>